import type { Event } from '@/interface/event'
import type { QuestionInterface } from '@/interface/question'
import type { CoinHistory, GiftHistory } from '@/interface/transaction'
import type { LeaderboardUser, UserInterface } from '@/interface/user'

export type UserRoleType = 'PARTICIPANT' | 'STAFF' | 'MODERATOR' | 'ADMIN'
export type EducationLevelType = 'M4' | 'M5' | 'M6' | 'Y1' | 'Y2' | 'Y3' | 'Y4' | 'GRADUATED'

export const SECONDARY_YEARS = ['4', '5', '6']
export const ACADEMIC_YEARS = ['1', '2', '3', '4', 'บัณฑิต']

export const mockGiftSending = 7
export const mockCostPerTicket = 500

export const mockUser: UserInterface = {
  id: '1',
  studentId: '329102',
  username: 'N001',
  firstname: 'แคนคะนวย',
  lastname: 'คงรวย คงทวยแทน',
  nickname: 'หัวแคน',
  educationLevel: 'M4',
  role: 'PARTICIPANT',
  school: 'Hua Can School',
  isResetUser: false,
  termsAcceptedAt: null,
  wallets: {
    coin_balance: 4000,
    coin_cumulative: 10000,
    gift_sends_remaining: 4,
  },
}

// export const mockLeaderboardUsers: LeaderboardUser[] = [];
export const mockLeaderboardUsers: LeaderboardUser[] = [
  {
    nickname: 'ชัย',
    role: 'PARTICIPANT',
    firstname: 'ชนะ',
    lastname: 'ผจญภัย',
    educationLevel: 'Y3',
    coin_cumulative: 105000,
  },
  {
    nickname: 'โอ',
    role: 'STAFF',
    firstname: 'เลสิก',
    lastname: 'ผจญภัย',
    educationLevel: 'Y4',
    coin_cumulative: 101200,
  },
  {
    nickname: 'โย',
    role: 'PARTICIPANT',
    firstname: 'ธนกฤต',
    lastname: 'พัฒนาวงศาคณาจารย์',
    educationLevel: 'Y3',
    coin_cumulative: 99500,
  },
  {
    nickname: 'ฟ้า',
    role: 'PARTICIPANT',
    firstname: 'ศิริพร',
    lastname: 'ขยันเรียน',
    educationLevel: 'Y3',
    coin_cumulative: 9700,
  },
  {
    nickname: 'แบงค์',
    role: 'STAFF',
    firstname: 'ธนาคาร',
    lastname: 'ออมสิน',
    educationLevel: 'Y4',
    coin_cumulative: 9500,
  },
  {
    nickname: 'มิว',
    role: 'PARTICIPANT',
    firstname: 'มิวสิค',
    lastname: 'อินเดอะซัน',
    educationLevel: 'Y2',
    coin_cumulative: 9350,
  },
  {
    nickname: 'เฟรม',
    role: 'STAFF',
    firstname: 'เฟรม',
    lastname: 'ทรงศักดิ์',
    educationLevel: 'Y4',
    coin_cumulative: 9200,
  },
  {
    nickname: 'ไผ่',
    role: 'PARTICIPANT',
    firstname: 'ไผ่',
    lastname: 'ร่มเย็น',
    educationLevel: 'Y3',
    coin_cumulative: 9050,
  },
  {
    nickname: 'ปอนด์',
    role: 'STAFF',
    firstname: 'ภาณุวัฒน์',
    lastname: 'ทองดี',
    educationLevel: 'Y4',
    coin_cumulative: 8900,
  },
  {
    nickname: 'เจน',
    role: 'PARTICIPANT',
    firstname: 'เจนจิรา',
    lastname: 'คิดไว',
    educationLevel: 'Y2',
    coin_cumulative: 8700,
  },
  {
    nickname: 'โบ๊ท',
    role: 'STAFF',
    firstname: 'นาวี',
    lastname: 'สมบูรณ์',
    educationLevel: 'Y4',
    coin_cumulative: 8600,
  },
  {
    nickname: 'เบล',
    role: 'PARTICIPANT',
    firstname: 'เบลล่า',
    lastname: 'วิริยะ',
    educationLevel: 'Y1',
    coin_cumulative: 8500,
  },
  {
    nickname: 'อาร์ต',
    role: 'STAFF',
    firstname: 'อัครเดช',
    lastname: 'ใจดี',
    educationLevel: 'Y3',
    coin_cumulative: 8450,
  },
  {
    nickname: 'อิง',
    role: 'PARTICIPANT',
    firstname: 'อิงฟ้า',
    lastname: 'ชื่นจิต',
    educationLevel: 'Y2',
    coin_cumulative: 8300,
  },
  {
    nickname: 'คิม',
    role: 'STAFF',
    firstname: 'คิมหันต์',
    lastname: 'สายลม',
    educationLevel: 'Y4',
    coin_cumulative: 8200,
  },
  {
    nickname: 'บอส',
    role: 'PARTICIPANT',
    firstname: 'ภาสกร',
    lastname: 'สุดหล่อ',
    educationLevel: 'Y3',
    coin_cumulative: 8100,
  },
  {
    nickname: 'แนน',
    role: 'STAFF',
    firstname: 'ธนันดา',
    lastname: 'มั่นใจ',
    educationLevel: 'Y4',
    coin_cumulative: 8000,
  },
  {
    nickname: 'เกด',
    role: 'PARTICIPANT',
    firstname: 'เกศินี',
    lastname: 'ช่างฝัน',
    educationLevel: 'Y2',
    coin_cumulative: 7950,
  },
  {
    nickname: 'ต้น',
    role: 'STAFF',
    firstname: 'ธนโชติ',
    lastname: 'วงศ์ดี',
    educationLevel: 'Y4',
    coin_cumulative: 7800,
  },
  {
    nickname: 'น้ำ',
    role: 'PARTICIPANT',
    firstname: 'น้ำผึ้ง',
    lastname: 'หวานใจ',
    educationLevel: 'Y1',
    coin_cumulative: 7750,
  },
  {
    nickname: 'แทน',
    role: 'STAFF',
    firstname: 'แทนไท',
    lastname: 'ใจเย็น',
    educationLevel: 'Y4',
    coin_cumulative: 7700,
  },
  {
    nickname: 'เมย์',
    role: 'PARTICIPANT',
    firstname: 'เมธาวี',
    lastname: 'สวยจริง',
    educationLevel: 'Y3',
    coin_cumulative: 7600,
  },
  {
    nickname: 'กาย',
    role: 'STAFF',
    firstname: 'กายศิริ',
    lastname: 'กตัญญู',
    educationLevel: 'Y4',
    coin_cumulative: 7550,
  },
  {
    nickname: 'มุก',
    role: 'PARTICIPANT',
    firstname: 'มุกดา',
    lastname: 'ใสซื่อ',
    educationLevel: 'Y1',
    coin_cumulative: 7400,
  },
  {
    nickname: 'บอล',
    role: 'STAFF',
    firstname: 'ณัฐพงศ์',
    lastname: 'แข็งแรง',
    educationLevel: 'Y3',
    coin_cumulative: 7350,
  },
  {
    nickname: 'นุ่น',
    role: 'PARTICIPANT',
    firstname: 'นุ่นนภา',
    lastname: 'จิตดี',
    educationLevel: 'Y3',
    coin_cumulative: 7200,
  },
  {
    nickname: 'ปาล์ม',
    role: 'STAFF',
    firstname: 'ปาล์ม',
    lastname: 'ศรีสุข',
    educationLevel: 'Y4',
    coin_cumulative: 7100,
  },
  {
    nickname: 'ตาล',
    role: 'PARTICIPANT',
    firstname: 'ตาล',
    lastname: 'ธันวา',
    educationLevel: 'Y2',
    coin_cumulative: 7000,
  },
  {
    nickname: 'พีท',
    role: 'STAFF',
    firstname: 'พีระชัย',
    lastname: 'จงดี',
    educationLevel: 'Y4',
    coin_cumulative: 6950,
  },
  {
    nickname: 'ไอซ์',
    role: 'PARTICIPANT',
    firstname: 'ไอซ์',
    lastname: 'พราวตา',
    educationLevel: 'Y1',
    coin_cumulative: 6800,
  },
  {
    nickname: 'ต้นน้ำ',
    role: 'STAFF',
    firstname: 'อนันต์',
    lastname: 'รักดี',
    educationLevel: 'Y4',
    coin_cumulative: 6700,
  },
  {
    nickname: 'กิ๊ฟ',
    role: 'PARTICIPANT',
    firstname: 'กิ๊ฟ',
    lastname: 'วรางค์',
    educationLevel: 'Y3',
    coin_cumulative: 6600,
  },
  {
    nickname: 'ภู',
    role: 'STAFF',
    firstname: 'ภูวนัย',
    lastname: 'ใจเด็ด',
    educationLevel: 'Y3',
    coin_cumulative: 6500,
  },
  {
    nickname: 'แพรว',
    role: 'PARTICIPANT',
    firstname: 'แพรวา',
    lastname: 'พรหมดี',
    educationLevel: 'Y2',
    coin_cumulative: 6400,
  },
  {
    nickname: 'บิ๊ก',
    role: 'STAFF',
    firstname: 'บิ๊กบอส',
    lastname: 'สง่างาม',
    educationLevel: 'Y4',
    coin_cumulative: 6300,
  },
  {
    nickname: 'พลอย',
    role: 'PARTICIPANT',
    firstname: 'พลอยไพลิน',
    lastname: 'ใสซื่อ',
    educationLevel: 'Y1',
    coin_cumulative: 6200,
  },
  {
    nickname: 'ก้อง',
    role: 'STAFF',
    firstname: 'ก้องภพ',
    lastname: 'ธรรมดี',
    educationLevel: 'Y4',
    coin_cumulative: 6150,
  },
  {
    nickname: 'น้ำหนึ่ง',
    role: 'PARTICIPANT',
    firstname: 'น้ำหนึ่ง',
    lastname: 'จิตใจงาม',
    educationLevel: 'Y3',
    coin_cumulative: 6100,
  },
  {
    nickname: 'ฟิวส์',
    role: 'STAFF',
    firstname: 'ณัฐวุฒิ',
    lastname: 'ตรงไปตรงมา',
    educationLevel: 'Y4',
    coin_cumulative: 6000,
  },
  {
    nickname: 'จูน',
    role: 'PARTICIPANT',
    firstname: 'จุฑารัตน์',
    lastname: 'รื่นเริง',
    educationLevel: 'Y2',
    coin_cumulative: 5900,
  },
  {
    nickname: 'แทนคุณ',
    role: 'STAFF',
    firstname: 'แทนคุณ',
    lastname: 'ศรีวัฒน์',
    educationLevel: 'Y3',
    coin_cumulative: 5800,
  },
  {
    nickname: 'มิน',
    role: 'PARTICIPANT',
    firstname: 'มินตรา',
    lastname: 'พิทักษ์',
    educationLevel: 'Y1',
    coin_cumulative: 5700,
  },
  {
    nickname: 'ซัน',
    role: 'STAFF',
    firstname: 'ศราวุฒิ',
    lastname: 'อรุณรุ่ง',
    educationLevel: 'Y4',
    coin_cumulative: 5600,
  },
  {
    nickname: 'แพท',
    role: 'PARTICIPANT',
    firstname: 'แพทริเซีย',
    lastname: 'พอเพียง',
    educationLevel: 'Y3',
    coin_cumulative: 5500,
  },
  {
    nickname: 'ไกด์',
    role: 'STAFF',
    firstname: 'กิตติศักดิ์',
    lastname: 'ทองแท้',
    educationLevel: 'Y4',
    coin_cumulative: 5400,
  },
  {
    nickname: 'นิด',
    role: 'PARTICIPANT',
    firstname: 'นิดา',
    lastname: 'สมใจ',
    educationLevel: 'Y2',
    coin_cumulative: 5300,
  },
  {
    nickname: 'โอม',
    role: 'STAFF',
    firstname: 'โอม',
    lastname: 'รักดี',
    educationLevel: 'Y4',
    coin_cumulative: 5200,
  },
  {
    nickname: 'ฝน',
    role: 'PARTICIPANT',
    firstname: 'ฝนทิพย์',
    lastname: 'ชุ่มฉ่ำ',
    educationLevel: 'Y1',
    coin_cumulative: 5100,
  },
  {
    nickname: 'ตูน',
    role: 'STAFF',
    firstname: 'อาทิตยา',
    lastname: 'อรุณรุ่ง',
    educationLevel: 'Y3',
    coin_cumulative: 5050,
  },
  {
    nickname: 'ไทม์',
    role: 'PARTICIPANT',
    firstname: 'ธันวา',
    lastname: 'เร็วไว',
    educationLevel: 'Y2',
    coin_cumulative: 4950,
  },
  {
    nickname: 'เฟียส',
    role: 'STAFF',
    firstname: 'เฟียส',
    lastname: 'พลังดี',
    educationLevel: 'Y4',
    coin_cumulative: 4900,
  },
  {
    nickname: 'อาย',
    role: 'PARTICIPANT',
    firstname: 'อารยา',
    lastname: 'วิชิต',
    educationLevel: 'Y3',
    coin_cumulative: 4800,
  },
  {
    nickname: 'แซม',
    role: 'STAFF',
    firstname: 'แซม',
    lastname: 'ศรีสวัสดิ์',
    educationLevel: 'Y3',
    coin_cumulative: 4700,
  },
  {
    nickname: 'บูม',
    role: 'PARTICIPANT',
    firstname: 'บูมบูม',
    lastname: 'ธัญญา',
    educationLevel: 'Y1',
    coin_cumulative: 4600,
  },
  {
    nickname: 'ฟาง',
    role: 'STAFF',
    firstname: 'ฟางข้าว',
    lastname: 'พงษ์ดี',
    educationLevel: 'Y4',
    coin_cumulative: 4500,
  },
  {
    nickname: 'เกรซ',
    role: 'PARTICIPANT',
    firstname: 'เกรซ',
    lastname: 'ศิลป์ดี',
    educationLevel: 'Y2',
    coin_cumulative: 4400,
  },
  {
    nickname: 'เพชร',
    role: 'STAFF',
    firstname: 'เพชร',
    lastname: 'แก้วงาม',
    educationLevel: 'Y4',
    coin_cumulative: 4300,
  },
  {
    nickname: 'แป้ง',
    role: 'PARTICIPANT',
    firstname: 'แป้งร่ำ',
    lastname: 'พรหมดี',
    educationLevel: 'Y1',
    coin_cumulative: 4200,
  },
  {
    nickname: 'เนม',
    role: 'STAFF',
    firstname: 'เนม',
    lastname: 'ภูวเดช',
    educationLevel: 'Y4',
    coin_cumulative: 4100,
  },
  {
    nickname: 'ออม',
    role: 'PARTICIPANT',
    firstname: 'ออมสิน',
    lastname: 'ใจงาม',
    educationLevel: 'Y2',
    coin_cumulative: 4000,
  },
]

export const participantQuestions: QuestionInterface[] = [
  {
    id: 'QN1',
    title: 'สนใจสายการเรียนไหนอยู่รึเปล่า?',
    answers: ['คณะสายวิทย์สุขภาพ', 'คณะสายวิทย์กายภาพ', 'คณะสายมนุษย์-สังคม'],
  },
  {
    id: 'QN2',
    title: 'ทำไมถึงสนใจเรียนต่อจุฬาฯ?',
    answers: [
      'เกย์จุฬา',
      'มอท็อปประเทศมันเฟี้ยว',
      'เพราะน้ำใจน้องพี่สีชมพู',
      'อยากยิ่งใหญ่ อยากเป็นเศรษฐี',
      'ดูคอนเนคชั่นดี ดูมีโอกาสมากกว่า',
      'อยากไปเรียนไกลบ้านบ้าง เบื่อเชียงใหม่',
      'พ่อแม่อยากให้เรียน',
      'ยังไม่ตัดสินใจ แวะมาหาความรู้เฉย ๆ',
      'ไม่รู้ แค่ชอบสีชมพูเฉย ๆ',
      'ไม่รู้ ตามเพื่อน',
    ],
  },
  {
    id: 'QN3',
    title: 'เป็นคนประเภทไหนในห้อง?',
    answers: [
      'ตั้งใจเรียนสุด ๆ',
      'ต้นฉบับการบ้าน',
      'เข้าทุกคาบแต่ไม่ทราบอะไรเลย',
      'สายหลับ หลับตลอดเวลา',
      'แก๊งเกมเมอร์ ว่างแล้วต้องตี้',
      'อยู่เงียบ ๆ แบบประหยัดพลังงาน',
      'สายฮา ตบมุกโบ๊ะบ๊ะ',
      'บ้าพลัง ชอบเล่นกีฬา',
      'Extrovert รู้จักคนทั้งโรงเรียน',
      'สายกิจกรรม งานอะไรพี่ไปหมด',
      'รักสวยรักงามแบบ Slay Energy',
      'พกความฝันไว้ในสมุดวาดเขียน',
      'มาโรงเรียนเพื่อเจอเพื่อน เข้าสังคม',
      '(มา)สายเสมอต้นเสมอปลาย',
      'ดาว TikTok',
    ],
  },
  {
    id: 'QN4',
    title: 'ชอบอะไรโรงเรียนตัวเองที่สุด?',
    answers: [
      'เข้มแข็งด้านวิชาการ',
      'หลักสูตรหลายอย่างน่าสนใจ',
      'เพื่อน ๆ น่ารัก',
      'นักเรียนมีแต่คนหน้าตาดี',
      'คุณครูใจดี สอนสนุก',
      'โรงอาหารข้าวอร่อย',
      'กิจกรรมในโรงเรียนแบบปึ้ง',
      'เครื่องแบบนักเรียนเกร๋มาก',
      'บรรยากาศดี',
      'ห้องสมุดคือ Safe zone',
      'เดินทางง่าย',
      'เพื่อน/รุ่นพี่/รุ่นน้อง คนนั้น ><',
      'ไม่รู้เหมือนกัน คิดไม่ออก',
    ],
  },
  {
    id: 'QN5',
    title: 'งานอดิเรกที่ชอบทำในช่วงนี้?',
    answers: [
      'นอน',
      'อ่านหนังสือ/นิยาย/การ์ตูน',
      'ดูหนัง/ซีรีส์/อนิเมะ',
      'เล่นเกม',
      'เล่นกีฬา',
      'ดู Youtube',
      'ออกไปเที่ยว',
      'เป็นวัยรุ่น TikTok',
      'ฟังเพลง',
      'ทำงานศิลปะ',
      'ร้องเพลง',
      'คราฟต์งานเขียน',
      'ถ่ายภาพ',
      'เล่นดนตรี',
      'ทำอะไรพีค ๆ ที่นอกจากในนี้',
    ],
  },
  {
    id: 'QN6',
    title: 'ถ้าพรุ่งนี้โลกแตกจะทำอะไร?',
    answers: [
      'นอน',
      'ร้องไห้ก่อน',
      'ทำงานอดิเรกที่ชอบ',
      'ออกไปกินของอร่อย',
      'ซื้อทุกอย่างที่อยากซื้อ',
      'สารภาพรักกับคนที่ชอบ',
      'ใช้เวลาอยู่กับแฟน',
      'ใช้เวลาอยู่กับเพื่อน',
      'ใช้เวลาอยู่กับครอบครัว',
      'ชิว แล้วผมจะไปแคร์(เห้)ไร',
      'ไปที่ ๆ อยากไป',
      'เคลียร์ทุกอย่างที่อยากทำแต่ไม่กล้า',
      'แกล้งบ้าดีกว่าพรี่',
    ],
  },
]

export const seniorQuestions: QuestionInterface[] = [
  {
    id: 'QS1',
    title: 'คิดยังไงกับคณะที่เรียนอยู่?',
    answers: [
      'สนุกมากกกกก',
      'เฉย ๆ อยู่ได้ ได้อยู่',
      'เรียนหนักแต่ไหว',
      'หนี F',
      'อยากลาออกทุกวัน',
    ],
  },
  {
    id: 'QS2',
    title: 'ทำไมถึงเลือกเรียนจุฬาฯ?',
    answers: [
      'เกย์จุฬา',
      'มอท็อปประเทศมันเฟี้ยว',
      'เพราะน้ำใจน้องพี่สีชมพู',
      'อยากยิ่งใหญ่ อยากเป็นเศรษฐี',
      'ดูคอนเนคชั่นดี ดูมีโอกาสมากกว่า',
      'อยากไปเรียนไกลบ้านบ้าง เบื่อจังหวัดตัวเอง',
      'พ่อแม่อยากให้เรียน',
      'ไม่รู้ แค่ชอบสีชมพูเฉย ๆ',
      'ไม่รู้ ตามเพื่อน',
    ],
  },
  {
    id: 'QS3',
    title: 'ทำไมถึงมาค่ายจุฬา-เชียงใหม่?',
    answers: [
      'อยากลองทำอะไรใหม่ ๆ',
      'เพื่อนชวน',
      'อยากมาเที่ยวเชียงใหม่',
      'อยากทำค่ายอยู่แล้ว',
      'เคยมาค่ายนี้ พอขึ้นมหาลัยเลยมาช่วย',
    ],
  },
  {
    id: 'QS4',
    title: 'อยากมีพลังวิเศษอะไรมากที่สุด?',
    answers: [
      'เป็นอมตะ',
      'รู้อดีต รู้อนาคต',
      'ลอยได้',
      'อ่านใจคน',
      'ฟังพูดอ่านเขียนได้ทุกภาษาบนโลก',
      'วาร์ปได้แบบไม่จำกัดระยะทาง',
      'ย้อนเวลา/หยุดเวลา',
      'มีพลังรักษาคนแบบ Healer',
      'ใช้เวทย์มนตร์',
      'คุยกับสัตว์',
    ],
  },
  {
    id: 'QS5',
    title: 'สถานะในตอนนึ้?',
    answers: [
      'ยังโสด โสด อยู่ทางนี้ยังโสด โสด',
      'มีแฟนแล้ว รักแฟนมาก',
      'กำลังพบเจอมรสุมชีวิต แต่พรี่ไหวอยู่(ไม่)',
      'ถึงตัวจะเป็นผู้ใหญ่ แต่สมองยังเป็นเด็ก',
      'กำลังเดินทางอยู่',
      'รู้สึกไม่อยากโตเป็นผู้ใหญ่',
      'สบายดี ชีวิตแฮปปี้ มีความสุข',
      'เฉย ๆ ไม่แย่ อยู่ได้',
      'อธิษฐานให้โลกแตกทุกวัน',
    ],
  },
  {
    id: 'QS6',
    title: 'ถ้าวันนั้นไม่ติดจุฬาจะทำยังไง?',
    answers: [
      'ร้องไห้ก่อน อย่างอื่นค่อยว่ากัน',
      'ยังไงก็ติดอยู่แล้ว เก่ง มั่นใจ ไม่กลัว',
      'ไปเรียนมหาลัยอื่นก็ได้ งอน',
      'ซิ่ว ฉันจะเป็นเด็กจุฬาฯให้ได้เลย!',
    ],
  },
  {
    id: 'QS7',
    title: 'ในค่ายนี้อยู่ฝ่ายอะไร?',
    answers: [
      'กิจกรรม',
      'ทะเบียน',
      'พี่กลุ่ม',
      'พยาบาล',
      'พิธีการ',
      'วิชาการ',
      'สถานที่',
      'สวัสดิการ-พัสดุ',
      'สันทนาการ',
      'แสงเสียง',
      'หาทุน',
      'PR',
      'Production',
      'Creative',
      'เหรัญญิก',
      'เลขา',
      'ประธาน',
    ],
  },
]

export const mockEvent: Event = {
  id: '1',
  name: 'กิจกรรมมหาเศรษฐี',
  coins: 100,
}

// export const mockCoinHistory: CoinHistory[] = [];
export const mockCoinHistory: CoinHistory[] = [
  {
    id: '1',
    name: 'บัญชีกลางค่ายจุฬา-เชียงใหม่',
    type: 'account',
    coins: 200,
    timestamp: new Date(),
  },
  {
    id: '2',
    name: 'กิจกรรมเปิดค่าย',
    type: 'event',
    coins: 50,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1),
  },
  {
    id: '3',
    name: 'กิจกรรม Ice Breaking',
    type: 'event',
    coins: 40,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: '4',
    name: 'กิจกรรมสันทนาการกลางคืน',
    type: 'event',
    coins: 60,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    id: '5',
    name: 'ณัฐชนน สงวนศรี',
    type: 'person',
    coins: 100,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: '6',
    name: 'ปพิชญา พรหมทา',
    type: 'person',
    coins: 80,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    id: '7',
    name: 'ศุภกร จิตตรง',
    type: 'person',
    coins: 120,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 7),
  },
  {
    id: '8',
    name: 'บัญชีกลางค่ายจุฬา-เชียงใหม่',
    type: 'account',
    coins: 200,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: '9',
    name: 'ธิดารัตน์ หอมจันทร์',
    type: 'person',
    coins: 90,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    id: '10',
    name: 'กิตติพงศ์ รัตนวดี',
    type: 'person',
    coins: 110,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: '11',
    name: 'ชนิกานต์ โชติวงศ์',
    type: 'person',
    coins: 95,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
  },
  {
    id: '12',
    name: 'สุรชัย แสงทอง',
    type: 'person',
    coins: 85,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1),
  },
]

// export const mockGiftHistory: GiftHistory[] = [];
export const mockGiftHistory: GiftHistory[] = [
  {
    id: '1',
    name: 'ณัฐชนน สงวนศรี',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: '2',
    name: 'ปพิชญา พรหมทา',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    id: '3',
    name: 'ศุภกร จิตตรง',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
  },
  {
    id: '4',
    name: 'ธิดารัตน์ หอมจันทร์',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: '5',
    name: 'กิตติพงศ์ รัตนวดี',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    id: '6',
    name: 'ชนิกานต์ โชติวงศ์',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    id: '7',
    name: 'สุรชัย แสงทอง',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10),
  },
  {
    id: '8',
    name: 'วริศรา ใจดี',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 15),
  },
  {
    id: '9',
    name: 'จิรายุส คำดี',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20),
  },
  {
    id: '10',
    name: 'พรนภา สมใจ',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
]
