import type { Event } from '@/interface/event'
import type { QuestionInterface } from '@/interface/question'
import type { CoinHistory, GiftHistory } from '@/interface/transaction'
import type { LeaderboardUser, UserInterface } from '@/interface/user'

export type UserRoleType = 'PARTICIPANT' | 'STAFF' | 'MODERATOR' | 'ADMIN'
export type EducationLevelType = 'M4' | 'M5' | 'M6' | 'Y1' | 'Y2' | 'Y3' | 'Y4' | 'GRADUATED'

export const SECONDARY_YEARS = ['4', '5', '6']
export const ACADEMIC_YEARS = ['1', '2', '3', '4', 'บัณฑิต']

export const mockGiftSending = 7
export const mockCostPerTicket = 500

export const mockJuniorUser: UserInterface = {
  id: '1',
  studentId: '329102',
  username: 'N001',
  firstname: 'แคนคะนวย',
  lastname: 'คงรวย คงทวยแทน',
  nickname: 'หัวแคน',
  education_level: 'M4',
  role: 'PARTICIPANT',
  school: 'Hua Can School',
  isResetUser: false,
  termsAcceptedAt: null,
  wallets: {
    coin_balance: 4000,
    coin_cumulative: 10000,
    gift_sends_remaining: 4,
  },
}

export const mockSeniorUser: UserInterface = {
  id: '2',
  studentId: '6612312321',
  username: 'P001',
  firstname: 'จ้าวทระนง',
  lastname: 'คงทวย คงควรคอย',
  nickname: 'หัวทวย',
  education_level: 'Y2',
  role: 'STAFF',
  school: 'Chulalongkorn University',
  isResetUser: false,
  termsAcceptedAt: null,
  wallets: {
    coin_balance: 2000,
    coin_cumulative: 12000,
    gift_sends_remaining: 4,
  },
}

// export const mockLeaderboardUsers: LeaderboardUser[] = [];
export const mockLeaderboardUsers: LeaderboardUser[] = [
  {
    nickname: 'ชัย',
    role: 'PARTICIPANT',
    firstname: 'ชนะ',
    lastname: 'ผจญภัย',
    education_level: 'Y3',
    coin_cumulative: 105000,
  },
  {
    nickname: 'โอ',
    role: 'STAFF',
    firstname: 'เลสิก',
    lastname: 'ผจญภัย',
    education_level: 'Y4',
    coin_cumulative: 101200,
  },
  {
    nickname: 'โย',
    role: 'PARTICIPANT',
    firstname: 'ธนกฤต',
    lastname: 'พัฒนาวงศาคณาจารย์',
    education_level: 'Y3',
    coin_cumulative: 99500,
  },
  {
    nickname: 'ฟ้า',
    role: 'PARTICIPANT',
    firstname: 'ศิริพร',
    lastname: 'ขยันเรียน',
    education_level: 'Y3',
    coin_cumulative: 9700,
  },
  {
    nickname: 'แบงค์',
    role: 'STAFF',
    firstname: 'ธนาคาร',
    lastname: 'ออมสิน',
    education_level: 'Y4',
    coin_cumulative: 9500,
  },
  {
    nickname: 'มิว',
    role: 'PARTICIPANT',
    firstname: 'มิวสิค',
    lastname: 'อินเดอะซัน',
    education_level: 'Y2',
    coin_cumulative: 9350,
  },
  {
    nickname: 'เฟรม',
    role: 'STAFF',
    firstname: 'เฟรม',
    lastname: 'ทรงศักดิ์',
    education_level: 'Y4',
    coin_cumulative: 9200,
  },
  {
    nickname: 'ไผ่',
    role: 'PARTICIPANT',
    firstname: 'ไผ่',
    lastname: 'ร่มเย็น',
    education_level: 'Y3',
    coin_cumulative: 9050,
  },
  {
    nickname: 'ปอนด์',
    role: 'STAFF',
    firstname: 'ภาณุวัฒน์',
    lastname: 'ทองดี',
    education_level: 'Y4',
    coin_cumulative: 8900,
  },
  {
    nickname: 'เจน',
    role: 'PARTICIPANT',
    firstname: 'เจนจิรา',
    lastname: 'คิดไว',
    education_level: 'Y2',
    coin_cumulative: 8700,
  },
  {
    nickname: 'โบ๊ท',
    role: 'STAFF',
    firstname: 'นาวี',
    lastname: 'สมบูรณ์',
    education_level: 'Y4',
    coin_cumulative: 8600,
  },
  {
    nickname: 'เบล',
    role: 'PARTICIPANT',
    firstname: 'เบลล่า',
    lastname: 'วิริยะ',
    education_level: 'Y1',
    coin_cumulative: 8500,
  },
  {
    nickname: 'อาร์ต',
    role: 'STAFF',
    firstname: 'อัครเดช',
    lastname: 'ใจดี',
    education_level: 'Y3',
    coin_cumulative: 8450,
  },
  {
    nickname: 'อิง',
    role: 'PARTICIPANT',
    firstname: 'อิงฟ้า',
    lastname: 'ชื่นจิต',
    education_level: 'Y2',
    coin_cumulative: 8300,
  },
  {
    nickname: 'คิม',
    role: 'STAFF',
    firstname: 'คิมหันต์',
    lastname: 'สายลม',
    education_level: 'Y4',
    coin_cumulative: 8200,
  },
  {
    nickname: 'บอส',
    role: 'PARTICIPANT',
    firstname: 'ภาสกร',
    lastname: 'สุดหล่อ',
    education_level: 'Y3',
    coin_cumulative: 8100,
  },
  {
    nickname: 'แนน',
    role: 'STAFF',
    firstname: 'ธนันดา',
    lastname: 'มั่นใจ',
    education_level: 'Y4',
    coin_cumulative: 8000,
  },
  {
    nickname: 'เกด',
    role: 'PARTICIPANT',
    firstname: 'เกศินี',
    lastname: 'ช่างฝัน',
    education_level: 'Y2',
    coin_cumulative: 7950,
  },
  {
    nickname: 'ต้น',
    role: 'STAFF',
    firstname: 'ธนโชติ',
    lastname: 'วงศ์ดี',
    education_level: 'Y4',
    coin_cumulative: 7800,
  },
  {
    nickname: 'น้ำ',
    role: 'PARTICIPANT',
    firstname: 'น้ำผึ้ง',
    lastname: 'หวานใจ',
    education_level: 'Y1',
    coin_cumulative: 7750,
  },
  {
    nickname: 'แทน',
    role: 'STAFF',
    firstname: 'แทนไท',
    lastname: 'ใจเย็น',
    education_level: 'Y4',
    coin_cumulative: 7700,
  },
  {
    nickname: 'เมย์',
    role: 'PARTICIPANT',
    firstname: 'เมธาวี',
    lastname: 'สวยจริง',
    education_level: 'Y3',
    coin_cumulative: 7600,
  },
  {
    nickname: 'กาย',
    role: 'STAFF',
    firstname: 'กายศิริ',
    lastname: 'กตัญญู',
    education_level: 'Y4',
    coin_cumulative: 7550,
  },
  {
    nickname: 'มุก',
    role: 'PARTICIPANT',
    firstname: 'มุกดา',
    lastname: 'ใสซื่อ',
    education_level: 'Y1',
    coin_cumulative: 7400,
  },
  {
    nickname: 'บอล',
    role: 'STAFF',
    firstname: 'ณัฐพงศ์',
    lastname: 'แข็งแรง',
    education_level: 'Y3',
    coin_cumulative: 7350,
  },
  {
    nickname: 'นุ่น',
    role: 'PARTICIPANT',
    firstname: 'นุ่นนภา',
    lastname: 'จิตดี',
    education_level: 'Y3',
    coin_cumulative: 7200,
  },
  {
    nickname: 'ปาล์ม',
    role: 'STAFF',
    firstname: 'ปาล์ม',
    lastname: 'ศรีสุข',
    education_level: 'Y4',
    coin_cumulative: 7100,
  },
  {
    nickname: 'ตาล',
    role: 'PARTICIPANT',
    firstname: 'ตาล',
    lastname: 'ธันวา',
    education_level: 'Y2',
    coin_cumulative: 7000,
  },
  {
    nickname: 'พีท',
    role: 'STAFF',
    firstname: 'พีระชัย',
    lastname: 'จงดี',
    education_level: 'Y4',
    coin_cumulative: 6950,
  },
  {
    nickname: 'ไอซ์',
    role: 'PARTICIPANT',
    firstname: 'ไอซ์',
    lastname: 'พราวตา',
    education_level: 'Y1',
    coin_cumulative: 6800,
  },
  {
    nickname: 'ต้นน้ำ',
    role: 'STAFF',
    firstname: 'อนันต์',
    lastname: 'รักดี',
    education_level: 'Y4',
    coin_cumulative: 6700,
  },
  {
    nickname: 'กิ๊ฟ',
    role: 'PARTICIPANT',
    firstname: 'กิ๊ฟ',
    lastname: 'วรางค์',
    education_level: 'Y3',
    coin_cumulative: 6600,
  },
  {
    nickname: 'ภู',
    role: 'STAFF',
    firstname: 'ภูวนัย',
    lastname: 'ใจเด็ด',
    education_level: 'Y3',
    coin_cumulative: 6500,
  },
  {
    nickname: 'แพรว',
    role: 'PARTICIPANT',
    firstname: 'แพรวา',
    lastname: 'พรหมดี',
    education_level: 'Y2',
    coin_cumulative: 6400,
  },
  {
    nickname: 'บิ๊ก',
    role: 'STAFF',
    firstname: 'บิ๊กบอส',
    lastname: 'สง่างาม',
    education_level: 'Y4',
    coin_cumulative: 6300,
  },
  {
    nickname: 'พลอย',
    role: 'PARTICIPANT',
    firstname: 'พลอยไพลิน',
    lastname: 'ใสซื่อ',
    education_level: 'Y1',
    coin_cumulative: 6200,
  },
  {
    nickname: 'ก้อง',
    role: 'STAFF',
    firstname: 'ก้องภพ',
    lastname: 'ธรรมดี',
    education_level: 'Y4',
    coin_cumulative: 6150,
  },
  {
    nickname: 'น้ำหนึ่ง',
    role: 'PARTICIPANT',
    firstname: 'น้ำหนึ่ง',
    lastname: 'จิตใจงาม',
    education_level: 'Y3',
    coin_cumulative: 6100,
  },
  {
    nickname: 'ฟิวส์',
    role: 'STAFF',
    firstname: 'ณัฐวุฒิ',
    lastname: 'ตรงไปตรงมา',
    education_level: 'Y4',
    coin_cumulative: 6000,
  },
  {
    nickname: 'จูน',
    role: 'PARTICIPANT',
    firstname: 'จุฑารัตน์',
    lastname: 'รื่นเริง',
    education_level: 'Y2',
    coin_cumulative: 5900,
  },
  {
    nickname: 'แทนคุณ',
    role: 'STAFF',
    firstname: 'แทนคุณ',
    lastname: 'ศรีวัฒน์',
    education_level: 'Y3',
    coin_cumulative: 5800,
  },
  {
    nickname: 'มิน',
    role: 'PARTICIPANT',
    firstname: 'มินตรา',
    lastname: 'พิทักษ์',
    education_level: 'Y1',
    coin_cumulative: 5700,
  },
  {
    nickname: 'ซัน',
    role: 'STAFF',
    firstname: 'ศราวุฒิ',
    lastname: 'อรุณรุ่ง',
    education_level: 'Y4',
    coin_cumulative: 5600,
  },
  {
    nickname: 'แพท',
    role: 'PARTICIPANT',
    firstname: 'แพทริเซีย',
    lastname: 'พอเพียง',
    education_level: 'Y3',
    coin_cumulative: 5500,
  },
  {
    nickname: 'ไกด์',
    role: 'STAFF',
    firstname: 'กิตติศักดิ์',
    lastname: 'ทองแท้',
    education_level: 'Y4',
    coin_cumulative: 5400,
  },
  {
    nickname: 'นิด',
    role: 'PARTICIPANT',
    firstname: 'นิดา',
    lastname: 'สมใจ',
    education_level: 'Y2',
    coin_cumulative: 5300,
  },
  {
    nickname: 'โอม',
    role: 'STAFF',
    firstname: 'โอม',
    lastname: 'รักดี',
    education_level: 'Y4',
    coin_cumulative: 5200,
  },
  {
    nickname: 'ฝน',
    role: 'PARTICIPANT',
    firstname: 'ฝนทิพย์',
    lastname: 'ชุ่มฉ่ำ',
    education_level: 'Y1',
    coin_cumulative: 5100,
  },
  {
    nickname: 'ตูน',
    role: 'STAFF',
    firstname: 'อาทิตยา',
    lastname: 'อรุณรุ่ง',
    education_level: 'Y3',
    coin_cumulative: 5050,
  },
  {
    nickname: 'ไทม์',
    role: 'PARTICIPANT',
    firstname: 'ธันวา',
    lastname: 'เร็วไว',
    education_level: 'Y2',
    coin_cumulative: 4950,
  },
  {
    nickname: 'เฟียส',
    role: 'STAFF',
    firstname: 'เฟียส',
    lastname: 'พลังดี',
    education_level: 'Y4',
    coin_cumulative: 4900,
  },
  {
    nickname: 'อาย',
    role: 'PARTICIPANT',
    firstname: 'อารยา',
    lastname: 'วิชิต',
    education_level: 'Y3',
    coin_cumulative: 4800,
  },
  {
    nickname: 'แซม',
    role: 'STAFF',
    firstname: 'แซม',
    lastname: 'ศรีสวัสดิ์',
    education_level: 'Y3',
    coin_cumulative: 4700,
  },
  {
    nickname: 'บูม',
    role: 'PARTICIPANT',
    firstname: 'บูมบูม',
    lastname: 'ธัญญา',
    education_level: 'Y1',
    coin_cumulative: 4600,
  },
  {
    nickname: 'ฟาง',
    role: 'STAFF',
    firstname: 'ฟางข้าว',
    lastname: 'พงษ์ดี',
    education_level: 'Y4',
    coin_cumulative: 4500,
  },
  {
    nickname: 'เกรซ',
    role: 'PARTICIPANT',
    firstname: 'เกรซ',
    lastname: 'ศิลป์ดี',
    education_level: 'Y2',
    coin_cumulative: 4400,
  },
  {
    nickname: 'เพชร',
    role: 'STAFF',
    firstname: 'เพชร',
    lastname: 'แก้วงาม',
    education_level: 'Y4',
    coin_cumulative: 4300,
  },
  {
    nickname: 'แป้ง',
    role: 'PARTICIPANT',
    firstname: 'แป้งร่ำ',
    lastname: 'พรหมดี',
    education_level: 'Y1',
    coin_cumulative: 4200,
  },
  {
    nickname: 'เนม',
    role: 'STAFF',
    firstname: 'เนม',
    lastname: 'ภูวเดช',
    education_level: 'Y4',
    coin_cumulative: 4100,
  },
  {
    nickname: 'ออม',
    role: 'PARTICIPANT',
    firstname: 'ออมสิน',
    lastname: 'ใจงาม',
    education_level: 'Y2',
    coin_cumulative: 4000,
  },
]

export const mockQuestions: QuestionInterface[] = [
  {
    id: '1',
    title: 'เลือกสายการเรียนที่สนใจที่สุด',
    answers: [
      'สายวิทย์-คณิต',
      'สายศิลป์-ภาษา',
      'สายศิลป์-คำนวณ',
      'สายศิลป์-สังคม',
      'สายอาชีพ / สายเทคโนโลยี',
    ],
  },
  {
    id: '2',
    title: 'ทำไมถึงสนใจเรียนต่อจุฬาฯ',
    answers: [
      'เพราะชื่อเสียงและมาตรฐานการเรียนการสอนของมหาวิทยาลัย',
      'เพราะอยากเจอสังคมที่มีความท้าทายและเพื่อนที่เก่ง',
      'เพราะมีคณะ/สาขาที่ตรงกับความสนใจ',
      'เพราะอยากอยู่ในสภาพแวดล้อมกลางเมืองที่สะดวก',
      'เพราะครอบครัวแนะนำหรือเป็นศิษย์เก่าจุฬาฯ',
    ],
  },
  {
    id: '3',
    title: 'เลือกเครื่องดื่มที่ชอบที่สุด',
    answers: ['ชาเย็น', 'กาแฟ', 'น้ำเปล่า', 'ชานมไข่มุก', 'น้ำผลไม้', 'โซดา / น้ำอัดลม'],
  },
]

export const mockEvent: Event = {
  id: '1',
  name: 'กิจกรรมมหาเศรษฐี',
  coins: 100,
}

// export const mockCoinHistory: CoinHistory[] = [];
export const mockCoinHistory: CoinHistory[] = [
  {
    id: '1',
    name: 'บัญชีกลางค่ายจุฬา-เชียงใหม่',
    type: 'account',
    coins: 200,
    timestamp: new Date(),
  },
  {
    id: '2',
    name: 'กิจกรรมเปิดค่าย',
    type: 'event',
    coins: 50,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1),
  },
  {
    id: '3',
    name: 'กิจกรรม Ice Breaking',
    type: 'event',
    coins: 40,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: '4',
    name: 'กิจกรรมสันทนาการกลางคืน',
    type: 'event',
    coins: 60,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    id: '5',
    name: 'ณัฐชนน สงวนศรี',
    type: 'person',
    coins: 100,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: '6',
    name: 'ปพิชญา พรหมทา',
    type: 'person',
    coins: 80,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    id: '7',
    name: 'ศุภกร จิตตรง',
    type: 'person',
    coins: 120,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 7),
  },
  {
    id: '8',
    name: 'บัญชีกลางค่ายจุฬา-เชียงใหม่',
    type: 'account',
    coins: 200,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: '9',
    name: 'ธิดารัตน์ หอมจันทร์',
    type: 'person',
    coins: 90,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    id: '10',
    name: 'กิตติพงศ์ รัตนวดี',
    type: 'person',
    coins: 110,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: '11',
    name: 'ชนิกานต์ โชติวงศ์',
    type: 'person',
    coins: 95,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
  },
  {
    id: '12',
    name: 'สุรชัย แสงทอง',
    type: 'person',
    coins: 85,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1),
  },
]

// export const mockGiftHistory: GiftHistory[] = [];
export const mockGiftHistory: GiftHistory[] = [
  {
    id: '1',
    name: 'ณัฐชนน สงวนศรี',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: '2',
    name: 'ปพิชญา พรหมทา',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    id: '3',
    name: 'ศุภกร จิตตรง',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
  },
  {
    id: '4',
    name: 'ธิดารัตน์ หอมจันทร์',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: '5',
    name: 'กิตติพงศ์ รัตนวดี',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    id: '6',
    name: 'ชนิกานต์ โชติวงศ์',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    id: '7',
    name: 'สุรชัย แสงทอง',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10),
  },
  {
    id: '8',
    name: 'วริศรา ใจดี',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 15),
  },
  {
    id: '9',
    name: 'จิรายุส คำดี',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20),
  },
  {
    id: '10',
    name: 'พรนภา สมใจ',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
]
