import type { Event } from "@/interface/event";
import type { Question } from "@/interface/question";
import type { CoinHistory, GiftHistory } from "@/interface/transaction";
import type { LeaderboardUser, UserInterface } from "@/interface/user";

export const JUNIOR_SENIOR_PATH = "/junior-senior";

export const mockJuniorUser: UserInterface = {
  studentId: "329102",
  username: "N001",
  firstname: "แคนคะนวย",
  lastname: "คงรวย คงทวยแทน",
  nickname: "หัวแคน",
  education_level: "มัธยม",
  year: "4",
  role: "junior",
  school: "Hua Can School",
  points: 4000,
  cumulative_points: 10000,
};

export const SECONDARY_YEARS = ["4", "5", "6"];
export const ACADEMIC_YEARS = ["1", "2", "3", "4", "บัณฑิต"];

export const mockSeniorUser: UserInterface = {
  studentId: "6612312321",
  username: "P001",
  firstname: "จ้าวทระนง",
  lastname: "คงทวย คงควรคอย",
  nickname: "หัวทวย",
  education_level: "มหาลัย",
  year: "2",
  role: "senior",
  school: "Chulalongkorn University",
  points: 6000,
  cumulative_points: 10000,
};

// export const mockLeaderboardUsers: LeaderboardUser[] = [];
export const mockLeaderboardUsers: LeaderboardUser[] = [
  {
    nickname: "ชัย",
    role: "junior",
    fullname: "ชนะ ผจญภัย",
    year: "3",
    cumulative_points: 105000,
  },
  {
    nickname: "โอ",
    role: "senior",
    fullname: "เลสิก ผจญภัย",
    year: "4",
    cumulative_points: 101200,
  },
  {
    nickname: "โย",
    role: "junior",
    fullname: "ธนกฤต พัฒนาวงศาคณาจารย์",
    year: "3",
    cumulative_points: 99500,
  },
  {
    nickname: "ฟ้า",
    role: "junior",
    fullname: "ศิริพร ขยันเรียน",
    year: "3",
    cumulative_points: 9700,
  },
  {
    nickname: "แบงค์",
    role: "senior",
    fullname: "ธนาคาร ออมสิน",
    year: "4",
    cumulative_points: 9500,
  },
  {
    nickname: "มิว",
    role: "junior",
    fullname: "มิวสิค อินเดอะซัน",
    year: "2",
    cumulative_points: 9350,
  },
  {
    nickname: "เฟรม",
    role: "senior",
    fullname: "เฟรม ทรงศักดิ์",
    year: "4",
    cumulative_points: 9200,
  },
  {
    nickname: "ไผ่",
    role: "junior",
    fullname: "ไผ่ ร่มเย็น",
    year: "3",
    cumulative_points: 9050,
  },
  {
    nickname: "ปอนด์",
    role: "senior",
    fullname: "ภาณุวัฒน์ ทองดี",
    year: "4",
    cumulative_points: 8900,
  },
  {
    nickname: "เจน",
    role: "junior",
    fullname: "เจนจิรา คิดไว",
    year: "2",
    cumulative_points: 8700,
  },
  {
    nickname: "โบ๊ท",
    role: "senior",
    fullname: "นาวี สมบูรณ์",
    year: "4",
    cumulative_points: 8600,
  },
  {
    nickname: "เบล",
    role: "junior",
    fullname: "เบลล่า วิริยะ",
    year: "1",
    cumulative_points: 8500,
  },
  {
    nickname: "อาร์ต",
    role: "senior",
    fullname: "อัครเดช ใจดี",
    year: "3",
    cumulative_points: 8450,
  },
  {
    nickname: "อิง",
    role: "junior",
    fullname: "อิงฟ้า ชื่นจิต",
    year: "2",
    cumulative_points: 8300,
  },
  {
    nickname: "คิม",
    role: "senior",
    fullname: "คิมหันต์ สายลม",
    year: "4",
    cumulative_points: 8200,
  },
  {
    nickname: "บอส",
    role: "junior",
    fullname: "ภาสกร สุดหล่อ",
    year: "3",
    cumulative_points: 8100,
  },
  {
    nickname: "แนน",
    role: "senior",
    fullname: "ธนันดา มั่นใจ",
    year: "4",
    cumulative_points: 8000,
  },
  {
    nickname: "เกด",
    role: "junior",
    fullname: "เกศินี ช่างฝัน",
    year: "2",
    cumulative_points: 7950,
  },
  {
    nickname: "ต้น",
    role: "senior",
    fullname: "ธนโชติ วงศ์ดี",
    year: "4",
    cumulative_points: 7800,
  },
  {
    nickname: "น้ำ",
    role: "junior",
    fullname: "น้ำผึ้ง หวานใจ",
    year: "1",
    cumulative_points: 7750,
  },
  {
    nickname: "แทน",
    role: "senior",
    fullname: "แทนไท ใจเย็น",
    year: "4",
    cumulative_points: 7700,
  },
  {
    nickname: "เมย์",
    role: "junior",
    fullname: "เมธาวี สวยจริง",
    year: "3",
    cumulative_points: 7600,
  },
  {
    nickname: "กาย",
    role: "senior",
    fullname: "กายศิริ กตัญญู",
    year: "4",
    cumulative_points: 7550,
  },
  {
    nickname: "มุก",
    role: "junior",
    fullname: "มุกดา ใสซื่อ",
    year: "1",
    cumulative_points: 7400,
  },
  {
    nickname: "บอล",
    role: "senior",
    fullname: "ณัฐพงศ์ แข็งแรง",
    year: "3",
    cumulative_points: 7350,
  },
  {
    nickname: "นุ่น",
    role: "junior",
    fullname: "นุ่นนภา จิตดี",
    year: "3",
    cumulative_points: 7200,
  },
  {
    nickname: "ปาล์ม",
    role: "senior",
    fullname: "ปาล์ม ศรีสุข",
    year: "4",
    cumulative_points: 7100,
  },
  {
    nickname: "ตาล",
    role: "junior",
    fullname: "ตาล ธันวา",
    year: "2",
    cumulative_points: 7000,
  },
  {
    nickname: "พีท",
    role: "senior",
    fullname: "พีระชัย จงดี",
    year: "4",
    cumulative_points: 6950,
  },
  {
    nickname: "ไอซ์",
    role: "junior",
    fullname: "ไอซ์ พราวตา",
    year: "1",
    cumulative_points: 6800,
  },
  {
    nickname: "ต้นน้ำ",
    role: "senior",
    fullname: "อนันต์ รักดี",
    year: "4",
    cumulative_points: 6700,
  },
  {
    nickname: "กิ๊ฟ",
    role: "junior",
    fullname: "กิ๊ฟ วรางค์",
    year: "3",
    cumulative_points: 6600,
  },
  {
    nickname: "ภู",
    role: "senior",
    fullname: "ภูวนัย ใจเด็ด",
    year: "3",
    cumulative_points: 6500,
  },
  {
    nickname: "แพรว",
    role: "junior",
    fullname: "แพรวา พรหมดี",
    year: "2",
    cumulative_points: 6400,
  },
  {
    nickname: "บิ๊ก",
    role: "senior",
    fullname: "บิ๊กบอส สง่างาม",
    year: "4",
    cumulative_points: 6300,
  },
  {
    nickname: "พลอย",
    role: "junior",
    fullname: "พลอยไพลิน ใสซื่อ",
    year: "1",
    cumulative_points: 6200,
  },
  {
    nickname: "ก้อง",
    role: "senior",
    fullname: "ก้องภพ ธรรมดี",
    year: "4",
    cumulative_points: 6150,
  },
  {
    nickname: "น้ำหนึ่ง",
    role: "junior",
    fullname: "น้ำหนึ่ง จิตใจงาม",
    year: "3",
    cumulative_points: 6100,
  },
  {
    nickname: "ฟิวส์",
    role: "senior",
    fullname: "ณัฐวุฒิ ตรงไปตรงมา",
    year: "4",
    cumulative_points: 6000,
  },
  {
    nickname: "จูน",
    role: "junior",
    fullname: "จุฑารัตน์ รื่นเริง",
    year: "2",
    cumulative_points: 5900,
  },
  {
    nickname: "แทนคุณ",
    role: "senior",
    fullname: "แทนคุณ ศรีวัฒน์",
    year: "3",
    cumulative_points: 5800,
  },
  {
    nickname: "มิน",
    role: "junior",
    fullname: "มินตรา พิทักษ์",
    year: "1",
    cumulative_points: 5700,
  },
  {
    nickname: "ซัน",
    role: "senior",
    fullname: "ศราวุฒิ อรุณรุ่ง",
    year: "4",
    cumulative_points: 5600,
  },
  {
    nickname: "แพท",
    role: "junior",
    fullname: "แพทริเซีย พอเพียง",
    year: "3",
    cumulative_points: 5500,
  },
  {
    nickname: "ไกด์",
    role: "senior",
    fullname: "กิตติศักดิ์ ทองแท้",
    year: "4",
    cumulative_points: 5400,
  },
  {
    nickname: "นิด",
    role: "junior",
    fullname: "นิดา สมใจ",
    year: "2",
    cumulative_points: 5300,
  },
  {
    nickname: "โอม",
    role: "senior",
    fullname: "โอม รักดี",
    year: "4",
    cumulative_points: 5200,
  },
  {
    nickname: "ฝน",
    role: "junior",
    fullname: "ฝนทิพย์ ชุ่มฉ่ำ",
    year: "1",
    cumulative_points: 5100,
  },
  {
    nickname: "ตูน",
    role: "senior",
    fullname: "อาทิตยา อรุณรุ่ง",
    year: "3",
    cumulative_points: 5050,
  },
  {
    nickname: "ไทม์",
    role: "junior",
    fullname: "ธันวา เร็วไว",
    year: "2",
    cumulative_points: 4950,
  },
  {
    nickname: "เฟียส",
    role: "senior",
    fullname: "เฟียส พลังดี",
    year: "4",
    cumulative_points: 4900,
  },
  {
    nickname: "อาย",
    role: "junior",
    fullname: "อารยา วิชิต",
    year: "3",
    cumulative_points: 4800,
  },
  {
    nickname: "แซม",
    role: "senior",
    fullname: "แซม ศรีสวัสดิ์",
    year: "3",
    cumulative_points: 4700,
  },
  {
    nickname: "บูม",
    role: "junior",
    fullname: "บูมบูม ธัญญา",
    year: "1",
    cumulative_points: 4600,
  },
  {
    nickname: "ฟาง",
    role: "senior",
    fullname: "ฟางข้าว พงษ์ดี",
    year: "4",
    cumulative_points: 4500,
  },
  {
    nickname: "เกรซ",
    role: "junior",
    fullname: "เกรซ ศิลป์ดี",
    year: "2",
    cumulative_points: 4400,
  },
  {
    nickname: "เพชร",
    role: "senior",
    fullname: "เพชร แก้วงาม",
    year: "4",
    cumulative_points: 4300,
  },
  {
    nickname: "แป้ง",
    role: "junior",
    fullname: "แป้งร่ำ พรหมดี",
    year: "1",
    cumulative_points: 4200,
  },
  {
    nickname: "เนม",
    role: "senior",
    fullname: "เนม ภูวเดช",
    year: "4",
    cumulative_points: 4100,
  },
  {
    nickname: "ออม",
    role: "junior",
    fullname: "ออมสิน ใจงาม",
    year: "2",
    cumulative_points: 4000,
  },
];

export const mockQuestions: Question[] = [
  {
    id: "1",
    title: "เลือกสายการเรียนที่สนใจที่สุด",
    answers: [
      "สายวิทย์-คณิต",
      "สายศิลป์-ภาษา",
      "สายศิลป์-คำนวณ",
      "สายศิลป์-สังคม",
      "สายอาชีพ / สายเทคโนโลยี",
    ],
  },
  {
    id: "2",
    title: "ทำไมถึงสนใจเรียนต่อจุฬาฯ",
    answers: [
      "เพราะชื่อเสียงและมาตรฐานการเรียนการสอนของมหาวิทยาลัย",
      "เพราะอยากเจอสังคมที่มีความท้าทายและเพื่อนที่เก่ง",
      "เพราะมีคณะ/สาขาที่ตรงกับความสนใจ",
      "เพราะอยากอยู่ในสภาพแวดล้อมกลางเมืองที่สะดวก",
      "เพราะครอบครัวแนะนำหรือเป็นศิษย์เก่าจุฬาฯ",
    ],
  },
  {
    id: "3",
    title: "เลือกเครื่องดื่มที่ชอบที่สุด",
    answers: [
      "ชาเย็น",
      "กาแฟ",
      "น้ำเปล่า",
      "ชานมไข่มุก",
      "น้ำผลไม้",
      "โซดา / น้ำอัดลม",
    ],
  },
];

export const mockEvent: Event = {
  id: "1",
  name: "กิจกรรมมหาเศรษฐี",
  coins: 100,
};

// export const mockCoinHistory: CoinHistory[] = [];
export const mockCoinHistory: CoinHistory[] = [
  {
    id: "1",
    name: "บัญชีกลางค่ายจุฬา-เชียงใหม่",
    type: "account",
    coins: 200,
    timestamp: new Date(),
  },
  {
    id: "2",
    name: "กิจกรรมเปิดค่าย",
    type: "event",
    coins: 50,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1),
  },
  {
    id: "3",
    name: "กิจกรรม Ice Breaking",
    type: "event",
    coins: 40,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "4",
    name: "กิจกรรมสันทนาการกลางคืน",
    type: "event",
    coins: 60,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    id: "5",
    name: "ณัฐชนน สงวนศรี",
    type: "person",
    coins: 100,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: "6",
    name: "ปพิชญา พรหมทา",
    type: "person",
    coins: 80,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    id: "7",
    name: "ศุภกร จิตตรง",
    type: "person",
    coins: 120,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 7),
  },
  {
    id: "8",
    name: "บัญชีกลางค่ายจุฬา-เชียงใหม่",
    type: "account",
    coins: 200,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: "9",
    name: "ธิดารัตน์ หอมจันทร์",
    type: "person",
    coins: 90,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    id: "10",
    name: "กิตติพงศ์ รัตนวดี",
    type: "person",
    coins: 110,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: "11",
    name: "ชนิกานต์ โชติวงศ์",
    type: "person",
    coins: 95,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
  },
  {
    id: "12",
    name: "สุรชัย แสงทอง",
    type: "person",
    coins: 85,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1),
  },
];

export const mockGiftHistory: GiftHistory[] = [];
// export const mockGiftHistory: GiftHistory[] = [
//   {
//     id: "1",
//     name: "ณัฐชนน สงวนศรี",
//     timestamp: new Date(Date.now() - 1000 * 60 * 30),
//   },
//   {
//     id: "2",
//     name: "ปพิชญา พรหมทา",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
//   },
//   {
//     id: "3",
//     name: "ศุภกร จิตตรง",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3),
//   },
//   {
//     id: "4",
//     name: "ธิดารัตน์ หอมจันทร์",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
//   },
//   {
//     id: "5",
//     name: "กิตติพงศ์ รัตนวดี",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
//   },
//   {
//     id: "6",
//     name: "ชนิกานต์ โชติวงศ์",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
//   },
//   {
//     id: "7",
//     name: "สุรชัย แสงทอง",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10),
//   },
//   {
//     id: "8",
//     name: "วริศรา ใจดี",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 15),
//   },
//   {
//     id: "9",
//     name: "จิรายุส คำดี",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20),
//   },
//   {
//     id: "10",
//     name: "พรนภา สมใจ",
//     timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
//   },
// ];
